language: ruby

rvm:
 - 2.0
 - 2.1.10
 - 2.2.5
 - 2.3.1

gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_latest_and_doorkeeper_latest.gemfile

matrix:
  exclude:
    - gemfile: gemfiles/rails_5_0.gemfile
      rvm: 2.1
    - gemfile: gemfiles/rails_latest_and_doorkeeper_latest.gemfile
      rvm: 2.1
  allowed_failures:
    - gemfile: gemfiles/rails_latest_and_doorkeeper_latest.gemfile
